### ISSUE TITLE
ReferenceError: Can't find variable: HoganTemplates

### ISSUE THREAD

**Issue by vvdpzz** [leshill/hogan_assets#1]
I have require hogan in application.js.
Rails 3.2.1 & Ruby 1.9.3p0

**Comment by leshill** [comment]
Hi,

This might be a JS ordering problem. The require statements should be in this order:

```
//= require hogan
//= require_tree templates
// ... other stuff
```

`HoganTemplates` gets defined with your templates, so it will only be available after the templates are loaded.

In development mode, you should see the template in your uncompressed `application.js`.

**Comment by vvdpzz** [comment]
I used it in backbone(0.5.3) and the require statements is this order:

<pre>
//= require jquery
//= require lib/underscore
//= require lib/backbone
//= require hogan
//= require backbone/app
</pre>

and here is `backbone/app` in coffee script

<pre>
#= require_self
#= require_tree ./templates
#= require_tree ./models
#= require_tree ./views
#= require_tree ./routers

window.App =
  Models: {}
  Collections: {}
  Routers: {}
  Views: {}
</pre>

I have a mustache template in `backbone/templates/index.mustache` and I called HoganTemplates like this

<pre>
App.Views.Posts ||= {}

class App.Views.Posts.IndexView extends Backbone.View
  template: HoganTemplates["backbone/templates/posts/index"]
...
</pre>

but... `ReferenceError: Can't find variable: HoganTemplates`

**Comment by leshill** [comment]
Hi,

Yea, move the templates require up above the `require_self`.

**Comment by olivierbuffon** [comment]
I've the same issue ... Did you find any solution to solve that problem ?
I tried to change order in application.js but without success.

**Comment by leshill** [comment]
Hi @olivierbuffon,

Interesting. Do you see the templates in your compiled JS files? Does your compiled JS have HoganTemplates in it?

**Comment by olivierbuffon** [comment]
Hi @leshill 

Yeah it's really strange ... Hogan.js is loaded but when I'm trying to find HoganTemplates through the code, I can't find it.
I tried multiple things to fix that, but I always have the same issue. 
I'm working on Rails 3.2.8, and to be honest for the moment I revert my project to the old fashion way ( using JST ).
If you have any idea I'll take it with pleasure.

**Comment by olivierbuffon** [comment]
Hey !
I've found my mistake ! :) The problem was caused by my template file ... I used templates named like template.html.hamstache ... So I just change that as template.hamstache and now everything is OK ! :+1: 

Hope it helps :)

**Comment by leshill** [comment]
Hi @olivierbuffon,

Interesting! Thanks
