### ISSUE TITLE
full template path included in compiled template

### ISSUE THREAD

**Issue by danielstocks** [leshill/hogan_assets#2]
Documentation says:

Templates are named for the sub-path below require_tree. For example, the file app/assets/javascripts/templates/pages/person.mustache will be named pages/person.

But the template gets named HoganTemplate["templates/pages/person"], would be nice to skip the "template" part

I'm including the templates from my app/asssets/javascripts/application.js with:
//= require_tree templates
the templates are located in app/asssets/javascripts/templates

Other than that: Thanks for a great tool!

**Comment by leshill** [comment]
Hi Daniel,

This sounds like a JS ordering issue. If you have something like this in your `application.js`:

```
//= require_tree .
//= require_tree templates
```

Then the templates are pulled in twice, once relative to `.` and once relative to `templates`.

Does that help?

**Comment by RSO** [comment]
Hi Les,

I encountered this same error, but it seems to be something different.

In the README (and in you comment here too) you talk about

``` javascript
//= require_tree templates
```

But this doesn't work in sprockets because it raises:

```
require_tree argument must be a relative path
```

So I use:

``` javascript
//= require_tree ./templates
```

Can it be this ./ causes the files to be included with their full path?

**Comment by RSO** [comment]
I fixed it for me by changing the path to `/app/assets/templates` and the require_tree directive to:

``` javascript
//= require_tree ../templates
```

and adding the following line to application.rb

``` ruby
config.assets.paths << "#{Rails.root}/app/assets/templates"
```

Which makes sure the /assets/templates directory is inside the sprockets include paths

**Comment by leshill** [comment]
Hi @RSO 

Nice, you pointed out the problem with `README`! The `README` says

```
 usually in app/assets/templates or app/assets/javascripts/templates
```

Obviously the first needs your config setting. I am taking that path out of the `README`.

Thanks

**Comment by RSO** [comment]
I'm wondering, does `//=require_tree templates` actually work for you?

 I see you referencing that line in here as well as in the README, but when I try that line it throws an error which states that the reference needs to be relative and thus start with a `.`.

**Comment by leshill** [comment]
Hi @RSO,

You are right, I just checked the sample app and it is:

```
//= require_tree ../templates
```

Updating the README now.

**Comment by RSO** [comment]
Glad I could help! Thanks! :D
