### ISSUE TITLE
Outdated hogan.js contains bug

### ISSUE THREAD

**Issue by guidobouman** [leshill/hogan_assets#20]
The version of hogan.js you're using contains the following bug:
https://github.com/twitter/hogan.js/issues/121

Can you please update your Gem with the newest version of hogan.js?

**Comment by leshill** [comment]
Hi @guidobouman,

Thanks for the heads up, updating now. In the future a PR makes it happen that much faster :)

**Comment by leshill** [comment]
Updated and gem pushed!

**Comment by guidobouman** [comment]
Will do in the future. My mind was jammed with some other issues at the time though.

Thanks for the fast fix!
