### ISSUE TITLE
lambda appears don't works

### ISSUE THREAD

**Issue by brunoguerra** [leshill/hogan_assets#21]
http://jsfiddle.net/czuxH/320/

simple example works on hogan.js site documentation, but, on hogan_asset, not true.

``` javascript
var template = "{{#wrapped}} {{name}} is awesome.{{/wrapped}} ";
var data = {
  "name": "Willy",
  "wrapped": function(context) {
    return "<b>"+context+"</b>";
  }
};

var hello = Hogan.compile(template);
console.log(hello.render(data));
$('#content').html(hello.render(data));
```

**Comment by AlexRiedler** [comment]
I tested this on Rails 3.1, 3.2, and 4.0 in all cases it worked perfectly.

> javascript console
> 
> ``` javascript
> var data = {
>   "name": "Willy",
>   "wrapped": function(context) {
>     return "<b>"+context+"</b>";
>   }
> };
> HoganTemplates['test'].render(data)
> ```
> 
> where test is the template name containing '"template" above,

did you forget to enable lambda support?

> config/intializers/hogan_assets.rb
> 
> ``` ruby
> HoganAssets::Config.configure do |config|
>   config.lambda_support = true
> end
> ```

Please indicate if you still need this working, and it is not and maybe I can provide further support!

**Comment by asumaran** [comment]
what's the correct definition of lambdas? 

In the mustache documentation (http://mustache.github.io/mustache.5.html) says

```
{
  "name": "Willy",
  "wrapped": function() {
    return function(text, render) {
      return "<b>" + render(text) + "</b>"
    }
  }
}
```

but hogan_assets doesn't work that way. it never pass the `render` argument

Why?

```
hogan_assets (1.6.0)
haml_assets (0.2.2)
rails (3.2.12)
haml (4.0.3)
haml-rails (0.4)
```

**Comment by leshill** [comment]
Hi @brunoguerra,

Does this help: https://github.com/leshill/hogan_assets#lambda-support ?
