### ISSUE TITLE
HoganTemplates is missing

### ISSUE THREAD

**Issue by davidbiehl** [leshill/hogan_assets#23]
I'm using Rails 4. I added the `hogan_assets` gem to my Gemfile, required `hogan` in my `application.js` manifest. When I render the page and view the source, I confirmed that `hogan.js` is included on the page. The directories that contain my templates are required in my `application.js` manifest as well. I have tried the `.mustache`, `.hamstache`, `.mustache.haml` extensions (with and without the `haml_assets` gem) It doesn't appear to be working.

When I render the page, it says that HoganTemplates is missing. I confirmed this through the console. I also noticed that none of my templates are included anywhere in the page, either referenced with script tags or otherwise. I think I have followed the instructions in the README pretty closely. Am I missing something?

**Comment by davidbiehl** [comment]
Nevermind, I found my problem.

I'm using modules and thought it would be nice to put the templates in the module's directory. So I had

```
index/index.hamstache
index/index.js.coffee
```

When sprockets compiled these, they both ended up as "index.js" to the server. Only the `index.js.coffee` file made it to the browser. I renamed `index.hamstache` to `template.hamstache` and it worked.

So, I'm not sure if this is a hogan_assets issue, or a sprockets issue ... but that's how I got around it.

**Comment by leshill** [comment]
Hi @davidbiehl,

Yea, that is a rough edge since it is not mentioned that template files are compiled to `name.js`.

**Comment by davidbiehl** [comment]
I was just surprised that it failed silently. I would have expected sprockets to detect the collision and raise some sort of error. That's not necessarily your problem, however. Oh well, thanks for responding, I'm enjoying the gem much more now :)
