### ISSUE TITLE
HTML contents converted to string?

### ISSUE THREAD

**Issue by sackIndian** [leshill/hogan_assets#24]
Hi,

I am using hogan with Fruitmachine.js,

Sample senario, Here i define modules as 

var Masthead = fruitmachine.define({
    name: 'masthead',
    template: templateMasthead,
});

var templateMasthead = Hogan.compile("{{title}}");

Now i provide json data for fruitmachine as

var layout = {
      module: 'masthead',
      model: {
        title: '<h6>Article viewer</h6><h2>Main name</h2>'
      }
    };

var view = fruitmachine(layout);
view
  .render()
  .inject(document.getElementById('app'))

when i inject view to div, it displays html tags along with string values?

How to handle these kind of situations?
(json response from server contains html tags)

Thank you,

**Comment by leshill** [comment]
Hi @sackIndian,

This might help? Take a look at the docs for [mustache](http://mustache.github.io/) and read about the difference between `{{` and `{{{`.

**Comment by sackIndian** [comment]
Thanks @leshill,

I have one more situation, what if i would like to refer external variable?

In above case if templateMasthead wants to refer some external variable:

var externalName1 = 'I am external';

var layout = {
module: 'masthead',
model: {
title: 'myTitle',
externalVar : 'externalName1'
}
};

var templateMasthead = Hogan.compile("{{title}} - {{externalVar}}");

#i can write { externalVar : 'I am external' }, but my intension is to place all values inside a single json object?

**Comment by leshill** [comment]
Hi @sackIndian,

The ideal for **mustache** is to have data already in the context. In this case, evaluate the variable when generating the context hash:

```
var layout = { …
  externalVar: externalName1,
  …
```

Good luck!

**Comment by sackIndian** [comment]
Thanks @leshill.
