### ISSUE TITLE
move to views?

### ISSUE THREAD

**Issue by cj** [leshill/hogan_assets#5]
Is it possible to grab the mustache templates from the views folder?

I'm trying to make it so rails can use the views too, by doing: 

``` ruby
module MustacheTemplateHandler
  def self.call(template)
    "Mustache.render(#{template.source.inspect}, Yajl::Encoder.encode(mustache)).html_safe"
  end
end
ActionView::Template.register_template_handler(:mustache, MustacheTemplateHandler)
```

**Comment by ajacksified** [comment]
Configurable folders would be great; I tried to get it working myself, but Sprockets threw errors when trying to load templates outside of the assets folder.

That said, you probably don't want to load from 'views'; if you're using mustache with Rails, the general pattern is to put your mustache files in a 'templates' folder and use the 'views' folder for ruby classes. I've seen this pattern with https://github.com/agoragames/stache and with https://github.com/goodmike/mustache_rails3.

**Comment by cj** [comment]
@ajacksified thank you for the quick reply :)  Is it possible to add a views path? i.e. if you wanted to add an assets path you would just do `config.assets.paths << "#{Rails.root}/app/assets/fonts"` like `config.views.paths << "#{Rails.root}/app/assets/templates"` or something...

**Comment by cj** [comment]
Ah I can do `ApplicationController.send(:append_view_path, Rails.root.join("app", "assets", "templates"))`

**Comment by leshill** [comment]
Closing this since it seems resolved?
