### ISSUE TITLE
Full path name required in HoganTemplates object

### ISSUE THREAD

**Issue by giantrobotbee** [leshill/hogan_assets#7]
I know there was a ticket before about this that seemed to be resolved, but for some reason, I have to provide the full pathname to my templates:

```
HoganTemplates['templates/home/index'].render()
```

Which renders the template at app/assets/javascripts/templates/home/index.mustache

My application.js file seems fine:

```
//= require hogan
//= require_tree ./templates
//= require_self
```

Am I missing something?

**Comment by leshill** [comment]
Hi @drmanitoba,

Yes, this is behavior that is mystifying to me and I should clarify in the README or do something about it.

Given `app/assets/javascripts/templates`, the proper require is `require_tree ./templates` or to grab everything `require_tree .` ; unfortunately that leads to the paths starting with `templates`.

Given `app/assets/templates`, the proper require is `require_tree ../templates` ; that leads to paths that _do not_ start with `templates`.

I cannot explain why `require_tree` works that way.

Sorry if that was confusing.
