### ISSUE TITLE
lambdas and precompiled templates

### ISSUE THREAD

**Issue by jweir** [leshill/hogan_assets#9]
I can get lambdas to working with the precompiled templates (but do work if compiled on the client site).

Maybe there is a work around?  Anyone else having an issue?

**Comment by leshill** [comment]
Hi @jweir,

Can you post some code for this?

**Comment by jweir** [comment]
Before you waste much time this looks like a Hogan.js issue https://github.com/twitter/hogan.js/issues/75

The template (saved as `test.mustache`)

```
Result: {{#add}}{{value}}{{/add}}
```

Client side compiled

```
Hogan.compile('Result: {{#add}}{{value}}{{/add}}').render({add:function(x){return "The value is "+x}, value:13})
```

returns

```
"Result: The value is 13"
```

With HoganTemplate

```
HoganTemplates['test'].render({add:function(x){return "The value is "+x}, value:13})
```

returns

```
"Result: 13
"
```

The `{{value}}` passes right through the lambda.

**Comment by leshill** [comment]
Hi @jweir,

Thanks for the update. I will try this later and see if there is anything obvious to be done on this side.

**Comment by gleuch** [comment]
The issues appears to be that not all the necessary parameters are being passed into Hogan.Template().

I have a fix for this in https://github.com/gleuch/hogan_assets/tree/hogan-3.0.0-template-lambda-fix

**Comment by leshill** [comment]
Hi @gleuch,

Thanks! I will take a look at this afternoon (slammed at the moment).

**Comment by leshill** [comment]
Hi @jweir and @gleuch,

I just pulled Greg's patch in. I decided to add a configuration option to turn this feature on (documented in the **README**):

```
HoganAssets::Config.configure do |config|
  config.lambda_support = true
end
```

I am ambivalent about whether it should be on or off by default. Let's see what other folks have to say.

**Comment by gleuch** [comment]
This sounds great. Likewise, I don't know what is best. Maybe off by default, so that the files themselves are smaller? Seems like extra bloat when a many number of people won't need it.

**Comment by jweir** [comment]
Thanks for the fix.  I haven't been able to test since I am away on holiday.  

I say have lambda_support on by default – least surprise.
